[project]
name = "eVLP-EM-Seq"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ipython>=8.28.0",
    "matplotlib>=3.9.2",
    "numpy>=2.1.1",
    "polars>=1.9.0",
]

[tool.ruff]
line-length = 80
